(require 'anything-startup)
(require 'anything-gtags)
(global-set-key (kbd "C-]") #'anything)
(global-set-key (kbd "C-,") #'abort-recursive-edit)
(global-set-key (kbd "C-x b") #'anything-buffers+)
(global-set-key (kbd "M-y") #'anything-show-kill-ring)
(global-set-key (kbd "M-.") #'anything-gtags-select)
(global-set-key (kbd "M-*") #'gtags-pop-stack)
(setq anything-gtags-enable-initial-pattern t)
(setq gtags-path-style 'relative)
(define-key anything-map (kbd "C-h") 'delete-backward-char)
(setq anything-candidate-number-limit 30)
(setq anything-quick-update t)
(setq anything-samewindow t)
(anything-read-string-mode '(buffer))
