(display-time)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(line-number-mode 1)
(column-number-mode 1)
(transient-mark-mode 1)
(show-paren-mode 1)
(global-hl-line-mode 1)
(setq initial-frame-alist
      '((top . 0) (left . 0) (width . 80) (height . 47)))
(when (require 'color-theme nil t)
  (color-theme-initialize)
  (color-theme-parus))
