(display-time)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(line-number-mode 1)
(column-number-mode 1)
(transient-mark-mode 1)
(show-paren-mode 1)
(global-hl-line-mode 1)
(set-face-background 'hl-line "floral white")
